<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Image extends Model
{
    //
    public $timestamps = true;
    public $table = 'images';

    public function insert(array $values)
    {
        return parent::insert($values); // TODO: Change the autogenerated stub
    }
    public function search_by_id($image_id){
        $data = Image::where('image_id',$image_id)->get();
        //$data = DB::table("images")->where('image_id', $image_id)->get();
        return $data;
    }
    public function search_by_menu_id($menu_id){
    	//$data = DB::table($table)->where('menu_id', $menu_id)->get();
        $data = Image::where('menu_id',$menu_id)->get();
    	return $data;
    }
}
