<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TmpMenus extends Model
{
   public $timestamps = true;
    public $table = 'tmpmenus';

    public function insert(array $values)
    {
        return parent::insert($values); // TODO: Change the autogenerated stub
    }
    public function search_by_id($menu_id){
        $data = TmpMenus::where('menu_id',$menu_id)->get();
        //$data = DB::table('tmpschool')->where('school_id', $school_id)->get();

        return $data;
    }
    public function search_by_menu_name($menu_name){
    	$data = TmpSchool::where('menu_name',$menu_name)->get();

    	return $data;
    }
    public function search_by_school_id($school_id){
    	$data = TmpSchool::where('school_id',$school_id)->get();

    	return $data;
    }   
}
