<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TmpSchool extends Model
{
    public $timestamps = true;
    public $table = 'tmpschools';

    public function insert(array $values)
    {
        return parent::insert($values); // TODO: Change the autogenerated stub
    }
    public function search_by_id($school_id){
        $data = TmpSchool::where('school_id',$school_id)->get();
        //$data = DB::table('tmpschool')->where('school_id', $school_id)->get();

        return $data;
    }
    public function search_by_school_name($school_name){
    	$data = TmpSchool::where('school_name',$school_name)->get();

    	return $data;
    } 
}
